export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAIL = 'GET_BLOGS_FAIL';

export const GET_SINGLE_BLOG_SUCCESS = 'GET_SINGLE_BLOG_SUCCESS';
export const GET_SINGLE_BLOG_FAIL = 'GET_SINGLE_BLOG_FAIL';

export const GET_SINGLE_COURSE_REVIEWS_SUCCESS =
	'GET_SINGLE_COURSE_REVIEWS_SUCCESS';
export const GET_SINGLE_COURSE_REVIEWS_FAIL = 'GET_SINGLE_COURSE_REVIEWS_FAIL';
