export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAIL = 'GET_BLOGS_FAIL';

export const GET_SINGLE_BLOG_SUCCESS = 'GET_SINGLE_BLOG_SUCCESS';
export const GET_SINGLE_BLOG_FAIL = 'GET_SINGLE_BLOG_FAIL';

export const GET_SINGLE_COURSE_REVIEWS_SUCCESS =
	'GET_SINGLE_COURSE_REVIEWS_SUCCESS';
export const GET_SINGLE_COURSE_REVIEWS_FAIL = 'GET_SINGLE_COURSE_REVIEWS_FAIL';

export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';
export const SET_QUERY_FILTER = 'SET_QUERY_FILTER';
export const REMOVE_QUERY_FILTER = 'REMOVE_QUERY_FILTER';
export const SET_FILTER = 'SET_FILTER';
