export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAIL = 'GET_BLOGS_FAIL';

export const GET_SINGLE_BLOG_SUCCESS = 'GET_SINGLE_BLOG_SUCCESS';
export const GET_SINGLE_BLOG_FAIL = 'GET_SINGLE_BLOG_FAIL';

export const GET_SINGLE_COURSE_REVIEWS_SUCCESS =
	'GET_SINGLE_COURSE_REVIEWS_SUCCESS';
export const GET_SINGLE_COURSE_REVIEWS_FAIL = 'GET_SINGLE_COURSE_REVIEWS_FAIL';

export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';
export const SET_QUERY_FILTER = 'SET_QUERY_FILTER';
export const REMOVE_QUERY_FILTER = 'REMOVE_QUERY_FILTER';
export const SET_FILTER = 'SET_FILTER';

export const CREATE_BLOG_COMMENT_SUCCESS = 'CREATE_BLOG_COMMENT_SUCCESS';
export const CREATE_BLOG_COMMENT_FAIL = 'CREATE_BLOG_COMMENT_FAIL';

export const GET_BLOG_COMMENT_SUCCESS = 'GET_BLOG_COMMENT_SUCCESS';
export const GET_BLOG_COMMENT_FAIL = 'GET_BLOG_COMMENT_FAIL';

export const DELETE_BLOG_COMMENT_SUCCESS = 'DELETE_BLOG_COMMENT_SUCCESS';
export const DELETE_BLOG_COMMENT_FAIL = 'DELETE_BLOG_COMMENT_FAIL';

export const UPDATE_BLOG_COMMENT_SUCCESS = 'UPDATE_BLOG_COMMENT_SUCCESS';
export const UPDATE_BLOG_COMMENT_FAIL = 'UPDATE_BLOG_COMMENT_FAIL';

export const GET_AUTO_COMPLETE_ALL_BLOG_SUCCESS =
	'GET_AUTO_COMPLETE_ALL_BLOG_SUCCESS';
export const GET_AUTO_COMPLETE_ALL_BLOG_FAIL =
	'GET_AUTO_COMPLETE_ALL_BLOG_FAIL';
