export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAIL = 'GET_SINGLE_COURSE_FAIL';

export const GET_SINGLE_COURSE_MODULES_SUCCESS =
	'GET_SINGLE_COURSE_MODULES_SUCCESS';
export const GET_SINGLE_COURSE_MODULES_FAIL = 'GET_SINGLE_COURSE_MODULES_FAIL';

export const GET_SINGLE_COURSE_REVIEWS_SUCCESS =
	'GET_SINGLE_COURSE_REVIEWS_SUCCESS';
export const GET_SINGLE_COURSE_REVIEWS_FAIL = 'GET_SINGLE_COURSE_REVIEWS_FAIL';
export const SET_FILTER = 'SET_FILTER';
export const SET_QUERY_FILTER = 'SET_QUERY_FILTER';
export const REMOVE_QUERY_FILTER = 'REMOVE_QUERY_FILTER';

export const GET_LECTURE_COURSE_SUCCESS = 'GET_LECTURE_COURSE_SUCCESS';
export const GET_LECTURE_COURSE_FAIL = 'GET_LECTURE_COURSE_FAIL';

export const GET_LECTURE_COURSE_MODULES_SUCCESS =
	'GET_LECTURE_COURSE_MODULES_SUCCESS';
export const GET_LECTURE_COURSE_MODULES_FAIL =
	'GET_LECTURE_COURSE_MODULES_FAIL';

export const GET_LECTURE_COURSE_REVIEWS_SUCCESS =
	'GET_LECTURE_COURSE_REVIEWS_SUCCESS';
export const GET_LECTURE_COURSE_REVIEWS_FAIL =
	'GET_LECTURE_COURSE_REVIEWS_FAIL';

export const CREATE_LECTURE_COURSE_SUCCESS = 'CREATE_LECTURE_COURSE_SUCCESS';
export const CREATE_LECTURE_COURSE_FAIL = 'CREATE_LECTURE_COURSE_FAIL';

export const GET_ACTIVE_COURSE_SUCCESS = 'GET_ACTIVE_COURSE_SUCCESS';
export const GET_ACTIVE_COURSE_FAIL = 'GET_ACTIVE_COURSE_FAIL';
