export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAIL = 'GET_COURSES_FAIL';

export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAIL = 'GET_SINGLE_COURSE_FAIL';

export const GET_SINGLE_COURSE_MODULES_SUCCESS =
	'GET_SINGLE_COURSE_MODULES_SUCCESS';
export const GET_SINGLE_COURSE_MODULES_FAIL = 'GET_SINGLE_COURSE_MODULES_FAIL';

export const GET_SINGLE_COURSE_REVIEWS_SUCCESS =
	'GET_SINGLE_COURSE_REVIEWS_SUCCESS';
export const GET_SINGLE_COURSE_REVIEWS_FAIL = 'GET_SINGLE_COURSE_REVIEWS_FAIL';
export const SET_FILTER = 'SET_FILTER';
