export const CREATE_ENROLLMENT_SUCCESS = 'CREATE_ENROLLMENT_SUCCESS';
export const CREATE_ENROLLMENT_FAIL = 'CREATE_ENROLLMENT_FAIL';

export const CHECK_ENROLLMENT_SUCCESS = 'CHECK_ENROLLMENT_SUCCESS';
export const CHECK_ENROLLMENT_FAIL = 'CHECK_ENROLLMENT_FAIL';

export const ENROLLMENT_CHECKING = 'ENROLLMENT_CHECKING';
export const ENROLLMENT_ENROLLING = 'ENROLLMENT_ENROLLING';
