export const GET_DASHBOARD_OVERVIEW_SUCCESS = 'GET_DASHBOARD_OVERVIEW_SUCCESS';
export const GET_DASHBOARD_OVERVIEW_FAIL = 'GET_DASHBOARD_OVERVIEW_FAIL';

export const GET_INSTRUCTOR_COURSES_SUCCESS = 'GET_INSTRUCTOR_COURSES_SUCCESS';
export const GET_INSTRUCTOR_COURSES_FAIL = 'GET_INSTRUCTOR_COURSES_FAIL';

export const UPDATE_INSTRUCTOR_PROFILE_SUCCESS = 'UPDATE_INSTRUCTOR_PROFILE_SUCCESS';
export const UPDATE_INSTRUCTOR_PROFILE_FAIL = 'UPDATE_INSTRUCTOR_PROFILE_FAIL';

export const SUBMIT_COURSE_FOR_REVIEW_SUCCESS = 'SUBMIT_COURSE_FOR_REVIEW_SUCCESS';
export const SUBMIT_COURSE_FOR_REVIEW_FAIL = 'SUBMIT_COURSE_FOR_REVIEW_FAIL';

export const GET_INSTRUCTOR_EARNINGS_SUCCESS = 'GET_INSTRUCTOR_EARNINGS_SUCCESS';
export const GET_INSTRUCTOR_EARNINGS_FAIL = 'GET_INSTRUCTOR_EARNINGS_FAIL';

export const GET_MY_INSTRUCTOR_PROFILE_SUCCESS = 'GET_MY_INSTRUCTOR_PROFILE_SUCCESS';
export const GET_MY_INSTRUCTOR_PROFILE_FAIL = 'GET_MY_INSTRUCTOR_PROFILE_FAIL';

export const SET_DASHBOARD_LOADING = 'SET_DASHBOARD_LOADING';
export const RESET_DASHBOARD_LOADING = 'RESET_DASHBOARD_LOADING';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';

export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';

export const GET_EDITING_COURSE_SUCCESS = 'GET_EDITING_COURSE_SUCCESS';
export const GET_EDITING_COURSE_FAIL = 'GET_EDITING_COURSE_FAIL';
export const CLEAR_EDITING_COURSE = 'CLEAR_EDITING_COURSE';

export const GET_ACTIVITY_FEED_SUCCESS = 'GET_ACTIVITY_FEED_SUCCESS';
export const GET_ACTIVITY_FEED_FAIL = 'GET_ACTIVITY_FEED_FAIL';

export const GET_ENGAGEMENT_HEATMAP_SUCCESS = 'GET_ENGAGEMENT_HEATMAP_SUCCESS';
export const GET_ENGAGEMENT_HEATMAP_FAIL = 'GET_ENGAGEMENT_HEATMAP_FAIL';
