export const GET_INSTRUCTORS_SUCCESS = 'GET_INSTRUCTORS_SUCCESS';
export const GET_INSTRUCTORS_FAIL = 'GET_INSTRUCTORS_FAIL';

export const GET_SINGLE_INSTRUCTOR_SUCCESS = 'GET_SINGLE_INSTRUCTOR_SUCCESS';
export const GET_SINGLE_INSTRUCTOR_FAIL = 'GET_SINGLE_INSTRUCTOR_FAIL';

export const CREATE_INSTRUCTOR_SUCCESS = 'CREATE_INSTRUCTOR_SUCCESS';
export const CREATE_INSTRUCTOR_FAIL = 'CREATE_INSTRUCTOR_FAIL';

export const UPDATE_INSTRUCTOR_SUCCESS = 'UPDATE_INSTRUCTOR_SUCCESS';
export const UPDATE_INSTRUCTOR_FAIL = 'UPDATE_INSTRUCTOR_FAIL';

export const DELETE_INSTRUCTOR_SUCCESS = 'DELETE_INSTRUCTOR_SUCCESS';
export const DELETE_INSTRUCTOR_FAIL = 'DELETE_INSTRUCTOR_FAIL';
