export const GET_USER_PUBLIC_PROFILE_SUCCESS =
	'GET_USER_PUBLIC_PROFILE_SUCCESS';
export const GET_USER_PUBLIC_PROFILE_FAIL = 'GET_USER_PUBLIC_PROFILE_FAIL';
export const RESET_USER_PUBLIC_PROFILE = 'RESET_USER_PUBLIC_PROFILE';
export const PUBLIC_PROFILE_CONST = 'publicProfile';
