export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_REVIEW_FAIL = 'GET_REVIEW_FAIL';

export const GET_COURSE_REVIEW_SUCCESS = 'GET_COURSE_REVIEW_SUCCESS';
export const GET_COURSE_REVIEW_FAIL = 'GET_COURSE_REVIEW_FAIL';

export const CREATE_COURSE_REVIEW_SUCCESS = 'CREATE_COURSE_REVIEW_SUCCESS';
export const CREATE_COURSE_REVIEW_FAIL = 'CREATE_COURSE_REVIEW_FAIL';

export const UPDATE_REVIEWS_SUCCESS = 'UPDATE_REVIEWS_SUCCESS';
export const UPDATE_REVIEWS_FAIL = 'UPDATE_REVIEWS_FAIL';

export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
