export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';

export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_FAIL = 'REMOVE_FROM_WISHLIST_FAIL';

export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL';

export const CHECK_WISHLIST_SUCCESS = 'CHECK_WISHLIST_SUCCESS';
export const CHECK_WISHLIST_FAIL = 'CHECK_WISHLIST_FAIL';
